//syntax version

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: grpcgo/grpcgo.proto

package grpcgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// the request message that contain three fields
type UserDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Age     int32  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *UserDataRequest) Reset() {
	*x = UserDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcgo_grpcgo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDataRequest) ProtoMessage() {}

func (x *UserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcgo_grpcgo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDataRequest.ProtoReflect.Descriptor instead.
func (*UserDataRequest) Descriptor() ([]byte, []int) {
	return file_grpcgo_grpcgo_proto_rawDescGZIP(), []int{0}
}

func (x *UserDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserDataRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UserDataRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

// the resopnse message container message and the use created data
type UserCreatedReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data    *UserDataRequest `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UserCreatedReply) Reset() {
	*x = UserCreatedReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcgo_grpcgo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCreatedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreatedReply) ProtoMessage() {}

func (x *UserCreatedReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpcgo_grpcgo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreatedReply.ProtoReflect.Descriptor instead.
func (*UserCreatedReply) Descriptor() ([]byte, []int) {
	return file_grpcgo_grpcgo_proto_rawDescGZIP(), []int{1}
}

func (x *UserCreatedReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserCreatedReply) GetData() *UserDataRequest {
	if x != nil {
		return x.Data
	}
	return nil
}

type ProductDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price int32  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *ProductDataRequest) Reset() {
	*x = ProductDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcgo_grpcgo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDataRequest) ProtoMessage() {}

func (x *ProductDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcgo_grpcgo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDataRequest.ProtoReflect.Descriptor instead.
func (*ProductDataRequest) Descriptor() ([]byte, []int) {
	return file_grpcgo_grpcgo_proto_rawDescGZIP(), []int{2}
}

func (x *ProductDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductDataRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ProductCreatedReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string              `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data    *ProductDataRequest `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ProductCreatedReply) Reset() {
	*x = ProductCreatedReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcgo_grpcgo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductCreatedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCreatedReply) ProtoMessage() {}

func (x *ProductCreatedReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpcgo_grpcgo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCreatedReply.ProtoReflect.Descriptor instead.
func (*ProductCreatedReply) Descriptor() ([]byte, []int) {
	return file_grpcgo_grpcgo_proto_rawDescGZIP(), []int{3}
}

func (x *ProductCreatedReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProductCreatedReply) GetData() *ProductDataRequest {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_grpcgo_grpcgo_proto protoreflect.FileDescriptor

var file_grpcgo_grpcgo_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x72, 0x70, 0x63, 0x67, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x67, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x67, 0x72, 0x70, 0x63, 0x67, 0x6f, 0x22, 0x51, 0x0a,
	0x0f, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65,
	0x22, 0x59, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2b,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x67, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3e, 0x0a, 0x12, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x5f, 0x0a, 0x13, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x67, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x49, 0x0a, 0x04,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x41, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x67, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x67, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x32, 0x55, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x12, 0x4a, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x12, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x67, 0x6f, 0x2e, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x67, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x10,
	0x5a, 0x0e, 0x67, 0x70, 0x72, 0x63, 0x2d, 0x67, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x67, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcgo_grpcgo_proto_rawDescOnce sync.Once
	file_grpcgo_grpcgo_proto_rawDescData = file_grpcgo_grpcgo_proto_rawDesc
)

func file_grpcgo_grpcgo_proto_rawDescGZIP() []byte {
	file_grpcgo_grpcgo_proto_rawDescOnce.Do(func() {
		file_grpcgo_grpcgo_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcgo_grpcgo_proto_rawDescData)
	})
	return file_grpcgo_grpcgo_proto_rawDescData
}

var file_grpcgo_grpcgo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpcgo_grpcgo_proto_goTypes = []interface{}{
	(*UserDataRequest)(nil),     // 0: grpcgo.UserDataRequest
	(*UserCreatedReply)(nil),    // 1: grpcgo.UserCreatedReply
	(*ProductDataRequest)(nil),  // 2: grpcgo.ProductDataRequest
	(*ProductCreatedReply)(nil), // 3: grpcgo.ProductCreatedReply
}
var file_grpcgo_grpcgo_proto_depIdxs = []int32{
	0, // 0: grpcgo.UserCreatedReply.data:type_name -> grpcgo.UserDataRequest
	2, // 1: grpcgo.ProductCreatedReply.data:type_name -> grpcgo.ProductDataRequest
	0, // 2: grpcgo.User.CreateUser:input_type -> grpcgo.UserDataRequest
	2, // 3: grpcgo.Product.CreateProduct:input_type -> grpcgo.ProductDataRequest
	1, // 4: grpcgo.User.CreateUser:output_type -> grpcgo.UserCreatedReply
	3, // 5: grpcgo.Product.CreateProduct:output_type -> grpcgo.ProductCreatedReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grpcgo_grpcgo_proto_init() }
func file_grpcgo_grpcgo_proto_init() {
	if File_grpcgo_grpcgo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcgo_grpcgo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcgo_grpcgo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCreatedReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcgo_grpcgo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcgo_grpcgo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductCreatedReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcgo_grpcgo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_grpcgo_grpcgo_proto_goTypes,
		DependencyIndexes: file_grpcgo_grpcgo_proto_depIdxs,
		MessageInfos:      file_grpcgo_grpcgo_proto_msgTypes,
	}.Build()
	File_grpcgo_grpcgo_proto = out.File
	file_grpcgo_grpcgo_proto_rawDesc = nil
	file_grpcgo_grpcgo_proto_goTypes = nil
	file_grpcgo_grpcgo_proto_depIdxs = nil
}
